# Funding options for VoxCore
# Uncomment and add your sponsorship links as applicable

# github: cliffmin  # GitHub Sponsors username
# ko_fi: username
# patreon: username
# custom: ["https://buymeacoffee.com/username", "https://example.com/donate"]

