#!/bin/bash
# Test script to verify F13 mode behaviors
# This simulates what happens with different key combinations

echo "F13 Mode Behavior Test"
echo "====================="
echo ""
echo "Configuration Summary (from ptt_config.lua):"
echo "--------------------------------------------"
grep -A3 "OUTPUT = {" ~/code/voxcore/hammerspoon/ptt_config.lua | sed 's/^/  /'
echo ""
echo "Expected Behaviors:"
echo "-------------------"
echo "1. F13 (hold) → sessionKind='hold', isShiftToggle=false"
echo "   → Uses OUTPUT.HOLD = { mode = 'paste', format = 'txt' }"
echo "   → Result: Text pastes at cursor (regardless of duration)"
echo ""
echo "2. F13 (double-tap) → sessionKind='toggle', isShiftToggle=false"  
echo "   → Uses OUTPUT.TOGGLE = { mode = 'paste', format = 'txt' }"
echo "   → Result: Text pastes at cursor (regardless of duration)"
echo ""
echo "3. Shift+F13 → sessionKind='toggle', isShiftToggle=true"
echo "   → Uses OUTPUT.SHIFT_TOGGLE = { mode = 'editor', format = 'md' }"
echo "   → Result: Opens markdown editor with formatted text"
echo ""
echo "Key Changes Made:"
echo "-----------------"
echo "✓ Added isShiftToggle flag to track Shift+F13 usage"
echo "✓ Updated OUTPUT configuration:"
echo "  - HOLD: paste/txt (F13 hold)"
echo "  - TOGGLE: paste/txt (F13 double-tap)" 
echo "  - SHIFT_TOGGLE: editor/md (Shift+F13)"
echo "✓ Modified output mode selection logic to check isShiftToggle"
echo ""
echo "Testing Instructions:"
echo "---------------------"
echo "1. Reload Hammerspoon configuration"
echo "2. Test F13 hold with short recording (5s) → should paste"
echo "3. Test F13 hold with long recording (30s) → should paste"
echo "4. Test F13 double-tap → should paste"
echo "5. Test Shift+F13 → should open markdown editor"
echo ""
echo "To reload Hammerspoon config:"
echo "  hs -c 'hs.reload()'"